### ISSUE TITLE
关于 readme.md 中 adguard ssr 及客户端IP 127.0.0.1 问题的一种解决。

### ISSUE THREAD

**Issue by wangliangliang2** [rufengsuixing/luci-app-adguardhome#102]
**readme 中的说明是以下**：
关于ssr配合

方法一gfw代理：dns重定向-作为dnsmasq的上游服务器
方法二gfw代理：手动设置adh上游dns为自己即127.0.0.1:[自己监听的端口]，然后使用 dns重定向-使用53端口替换dnsmasq，（因为端口互换后就是dnsmasq为上游了）
方法三国外ip代理：任意重定向方式，adh加入gfw列表，开启计划任务定时更新gfw即可
方法四gfw代理：dns重定向-重定向53端口到AdGuardHome,设置adh上游dns 为127.0.0.1:53

**提出的新解决方案是如下**：
1. 127.0.0.1 的客户端ip问题，dns重定向-重定向53端口到AdGuardHome 或者直接设置53端口到AdGuardHome （与原有的解决方案无异，在此只是顺带提下。）
2. 在解决127.0.0.1的基础上，要使用vpn 之类的 只要设置 AdGuardHome 的上游为 DNS over HTTPS (简称 DoH )和 DNS over TLS (简称 DoT )即可。目的是得到真实有效的ip。
此方案自觉得比以上四种方案都要好些。大家可以尝试下。

**Comment by kkfuzi** [comment]
发现一个问题。
SSR+搭配AGH，SSR+模式 绕过大陆IP，DNS解析是PDNSD
发现如果ADH设置成“使用53端口替换 dnsmasq” 或者“重定向53端口到AdGuardHome”模式， SSR+的访问控制/白名单 无效，设置成白名单的国外域名依然走代理。

如果ADH设置成“作为dnsmasq的上游服务器” 就好了。。。

但用上游服务器模式就没法统计局域网客户端信息和自定义客户端的广告过滤。。。
