### ISSUE TITLE
LAN client AGH.

### ISSUE THREAD

**Issue by spothz** [rufengsuixing/luci-app-adguardhome#103]
Hi friend, I am using your AGH script for openwrt. there is a problem with configuring clients on the local network. not how it is impossible to assign port 53 for AGH. tried various settings. changed dnsmasq port, but it does not help, 1745 port is assigned automatically after reboot. what could be the problem?

**Comment by spot320** [comment]
嗨，朋友，我正在將您的AGH腳本用於openwrt。 在本地網絡上配置客戶端時出現問題。 不是不可能為AGH分配端口53。 嘗試了各種設置。 更改了dnsmasq端口，但無濟於事，重新啟動後會自動分配1745端口。 可能是什麼問題呢？

**Comment by spot320** [comment]
> Hi friend, I am using your AGH script for openwrt. there is a problem with configuring clients on the local network. not how it is impossible to assign port 53 for AGH. tried various settings. changed dnsmasq port, but it does not help, 1745 port is assigned automatically after reboot. what could be the problem?
