### ISSUE TITLE
Unable to install adguardhome

### ISSUE THREAD

**Issue by green1052** [rufengsuixing/luci-app-adguardhome#119]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [V] I am running the latest version of luci-app-adguardhome
- [V] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home luci:**
  * 
* **Version of AdGuard Home server:**
  * 
* **Operating system and version:**
  *  OpenWrt SNAPSHOT r16178-1cd098784e / LuCI Master git-21.060.51374-cd06e70

### Expected Behavior

Unable to install adguardhome

### Actual Behavior

``` Local version: ., cloud version: v0.105.2
v0.105.2
v0.105.2
v0.105.2
v0.105.2
v0.105.2
v0.105.2
v5.
v0.105.2
v5.
v6.
v0.105.2
v6.
v7.
v0.105.2
v7.
v0.105.2
v0.105.2
v0.105.2
v5.
v0.105.2
v5.
v6.
v0.105.2
v6.
v7.
v0.105.2
v7.
v0.105.2
v0.105.2
v0.105.2
v0.105.2
v0.105.2
v0.105.2
v0.105.2
v0.105.2.
Updating core...
start download
/usr/share/AdGuardHome/update_core.sh: line 168: wget-ssl: not found
download failed try another download
/usr/share/AdGuardHome/update_core.sh: line 168: wget-ssl: not found
download failed try another download
no download success
```

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by 1nfsr** [comment]
#101 try this

**Comment by green1052** [comment]
thx
