### ISSUE TITLE
关于AdGuardHome的统计数据在路由重启后被重置

### ISSUE THREAD

**Issue by garypang13** [rufengsuixing/luci-app-adguardhome#14]
在root/etc/init.d/AdGuardHome中找到
		if [ ! -L $workdir/data/stats.db ]; then
		mv -f $workdir/data/stats.db /tmp/stats.db
		ln -s /tmp/stats.db $workdir/data/stats.db
		fi
这样把stats.db目录改到/tmp下,会导致每次重启路由AdGuardHome的统计数据就会被重置,这个数据的保存时间在后台就可以设定,不需要这样强制改为每次重启后重置,建议删除这几行代码.

**Comment by rufengsuixing** [comment]
你删了你就启动不了了看readme的已知问题相关

**Comment by garypang13** [comment]
> 你删了你就启动不了了看readme的已知问题相关，请自行修改工作目录

我测试过了,删除后能正常启动,

**Comment by rufengsuixing** [comment]
输出你的mount命令结果，和你的工作目录

**Comment by garypang13** [comment]
![12](https://user-images.githubusercontent.com/48883331/70121465-9434e500-16a9-11ea-9e80-b9cb49971f17.png)
![12](https://user-images.githubusercontent.com/48883331/70121517-b62e6780-16a9-11ea-9024-96e51c3315ad.png)

**Comment by rufengsuixing** [comment]
用最新的release尝试一下

**Comment by garypang13** [comment]
可以了,感谢!

**Comment by Mosney** [comment]
@garypang13 请问你上面截图用的什么软件
