### ISSUE TITLE
dns重定向重定向选择none后选项消失

### ISSUE THREAD

**Issue by simpleoo0o** [rufengsuixing/luci-app-adguardhome#141]
### 提交之前

在你提交问题之前请回答以下问题
**你可以删掉提交之前这个部分**

- [x] 我用着最新版的 luci-app-adguardhome
- [x] 我检查了没有人提交同样的问题

### 问题详细信息

* **AdGuard Home luci的版本:**
  * 
* **AdGuard Home server的版本:**
  * 
* **操作系统和版本:**
  * 

### 截图

![image](https://github.com/rufengsuixing/luci-app-adguardhome/assets/23304206/4995eb7a-62d8-4548-925a-b6e65ef3c4c5)

<details><summary>截图:</summary>

</details>

**Comment by handbye** [comment]
一样的问题，请问怎么恢复呢

**Comment by simpleoo0o** [comment]
最下面更多选项中可以加回来
