### ISSUE TITLE
部分语句等号判断与赋值搞混

### ISSUE THREAD

**Issue by liyiecho** [rufengsuixing/luci-app-adguardhome#15]
如果没搞错的话，以下这几个应该用==
https://github.com/rufengsuixing/luci-app-adguardhome/blob/0ac1c9ec56eb9e5e448a38087ee065b7336a0a56/root/etc/init.d/AdGuardHome#L25
https://github.com/rufengsuixing/luci-app-adguardhome/blob/0ac1c9ec56eb9e5e448a38087ee065b7336a0a56/root/etc/init.d/AdGuardHome#L183
https://github.com/rufengsuixing/luci-app-adguardhome/blob/0ac1c9ec56eb9e5e448a38087ee065b7336a0a56/root/etc/init.d/AdGuardHome#L185

**Comment by rufengsuixing** [comment]
```
a="123"
[root@xzb:/root]#if [ "$a" = "456" ]; then
> echo lll
> fi
[root@xzb:/root]#echo $a
123
[root@xzb:/root]#if [ "$a" = "123" ]; then
> echo lll
> fi
lll

```
