### ISSUE TITLE
adg可用的配置模板建议

### ISSUE THREAD

**Issue by RealKiro** [rufengsuixing/luci-app-adguardhome#17]
https://github.com/project-openwrt/openwrt/tree/master/package/jsda/AdGuardHome/files/conf

**Comment by rufengsuixing** [comment]
如果未来adh加入了内容过滤器而且性能足够大多数的路由器开启（估计是不可能233），我会考虑默认启用而且挑优加入少数几个规则

**Comment by Mosney** [comment]
> https://github.com/project-openwrt/openwrt/tree/master/package/jsda/AdGuardHome/files/conf

这个配置文件用到的过滤规则多且无用，估计维护者也是无脑堆砌的。
