### ISSUE TITLE
建议将“启用广告屏蔽”修改为“启用”

### ISSUE THREAD

**Issue by Mosney** [rufengsuixing/luci-app-adguardhome#18]
> https://github.com/rufengsuixing/luci-app-adguardhome/blob/bac903c118f92593de9e425cc688d438717980cd/luasrc/model/cbi/AdGuardHome/base.lua#L26

“启用广告屏蔽”可能会与ADG中的“禁用保护”“启用保护”功能混淆，
建议像大部分luci应用一样只留一个简单的`启用`勾选框即可。

![image](https://user-images.githubusercontent.com/22477230/70261742-0bfc3000-17ce-11ea-87ac-837b4463d52d.png)

![image](https://user-images.githubusercontent.com/22477230/70261689-ef5ff800-17cd-11ea-814c-9aabc9dccb1b.png)

**Comment by Mosney** [comment]
另外日志页的“备份”改为“下载日志‘更加直观

**Comment by rufengsuixing** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/commit/42ea6b71f5b1f72f4e1d209634480157758fc79a
