### ISSUE TITLE
这玩意的依赖是自动下载，安装的吗？

### ISSUE THREAD

**Issue by adaaaaaa** [rufengsuixing/luci-app-adguardhome#19]
求个教程。。。
makefile不太会看。。。依赖在哪，会自动去下载安装上？还是要自己去手动下载AdGuardHome？？

**Comment by rufengsuixing** [comment]
请下载release

**Comment by adaaaaaa** [comment]
> 请下载release，使用opkg安装

就仅仅只装你的luci-app-adguardhome就行了？
我是用Github Actions在线编译的L大固件。。。你看看我的配置，可以吗？

**Comment by rufengsuixing** [comment]
我发现还是需要一个wget依赖，你试着装一下，l大默认装wget

**Comment by Mosney** [comment]
> 我发现还是需要一个wget依赖，你试着装一下，l大默认装wget

可以替换成curl，官方的最小预编译包也是包含的

**Comment by rufengsuixing** [comment]
我记得貌似curl每次都是我手动下的，貌似不是默认选择的
