### ISSUE TITLE
没有日志文件时log页面报错，下载时github dns解析失败

### ISSUE THREAD

**Issue by adaaaaaa** [rufengsuixing/luci-app-adguardhome#22]
1.上次检测到的主程序版本: no config no bin 

2.AdGuardHome 执行文件路径 如果没有执行文件将自动下载 
我在L大的固件里面看，确实没有/usr/bin/AdGuardHome/AdGuardHome，也没有下载。。。
怎么回事？

3.	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	[C]: in function 'assert'
stack traceback:
/usr/lib/lua/luci/controller/AdGuardHome.lua:51: attempt to index global 'f' (a nil value)
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute call dispatcher target for entry '/admin/services/AdGuardHome/getlog'.	

4.Sun Dec  8 16:41:14 2019 daemon.err uhttpd[3162]: grep: /etc/AdGuardHome.yaml: No such file or directory
Sun Dec  8 16:41:17 2019 daemon.err uhttpd[3162]: uci: Entry not found
Sun Dec  8 16:41:27 2019 daemon.err uhttpd[3162]: --2019-12-08 16:41:27--  https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.99.3/AdGuardHome_linux_amd64.tar.gz
Sun Dec  8 16:41:32 2019 daemon.err uhttpd[3162]: Resolving github.com... failed: Try again.
Sun Dec  8 16:41:32 2019 daemon.err uhttpd[3162]: wget-ssl: unable to resolve host address 'github.com'
Sun Dec  8 16:41:32 2019 daemon.err uhttpd[3162]: tar: invalid magic
Sun Dec  8 16:41:32 2019 daemon.err uhttpd[3162]: tar: short read
Sun Dec  8 16:42:17 2019 daemon.err uhttpd[3162]: grep: /etc/AdGuardHome.yaml: No such file or directory
Sun Dec  8 16:42:17 2019 daemon.err uhttpd[3162]: awk: /etc/AdGuardHome.yaml: No such file or directory
Sun Dec  8 16:42:17 2019 daemon.err uhttpd[3162]: uci: Entry not found
Sun Dec  8 16:42:25 2019 daemon.err uhttpd[3162]: /usr/lib/lua/luci/dispatcher.lua:381: Failed to execute call dispatcher target for entry '/admin/services/AdGuardHome/getlog'.
Sun Dec  8 16:42:25 2019 daemon.err uhttpd[3162]: The called action terminated with an exception:
Sun Dec  8 16:42:25 2019 daemon.err uhttpd[3162]: /usr/lib/lua/luci/controller/AdGuardHome.lua:51: attempt to index global 'f' (a nil value)
Sun Dec  8 16:42:25 2019 daemon.err uhttpd[3162]: stack traceback:
Sun Dec  8 16:42:25 2019 daemon.err uhttpd[3162]: 	[C]: in function 'assert'
Sun Dec  8 16:42:25 2019 daemon.err uhttpd[3162]: 	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
Sun Dec  8 16:42:25 2019 daemon.err uhttpd[3162]: 	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>
Sun Dec  8 16:42:28 2019 daemon.err uhttpd[3162]: /usr/lib/lua/luci/dispatcher.lua:381: Failed to execute call dispatcher target for entry '/admin/services/AdGuardHome/getlog'.
Sun Dec  8 16:42:28 2019 daemon.err uhttpd[3162]: The called action terminated with an exception:
Sun Dec  8 16:42:28 2019 daemon.err uhttpd[3162]: /usr/lib/lua/luci/controller/AdGuardHome.lua:51: attempt to index global 'f' (a nil value)

**Comment by rufengsuixing** [comment]
已经尝试下载了，然而dns有问题失败了，日志中不是有
Resolving github.com... failed: Try again.

**Comment by rufengsuixing** [comment]
另一个是程序没启动没日志的时候尝试打开日志会报错

**Comment by rufengsuixing** [comment]
我会试着用其他的dns进行解析

**Comment by rufengsuixing** [comment]
执行文件下载需要勾选enable

**Comment by rufengsuixing** [comment]
请告诉我，你勾选的重定向设置

**Comment by adaaaaaa** [comment]
> 请告诉我，你勾选的重定向设置

没有做任何设置啊。。。都是默认的。。。
DNS好像没问题也。。。诊断能ping通。。。

**Comment by rufengsuixing** [comment]
github.com确实有被干扰的现象
另外你给的信息太少，我无法判断问题，
如果出现这个的时候是开机时，可能是启动顺序早于了dnsmasq，然而现在并不能确定

**Comment by rufengsuixing** [comment]
wget 不能用其他dns进行解析，所以只能加多尝试次数

**Comment by adaaaaaa** [comment]
> 可能是启动顺序早于了dnsmasq

开机顺序也会导致问题？？
你还需要知道什么信息？

**Comment by rufengsuixing** [comment]
如果不能复现就算了吧，有的dns第一次查询确实会超时，之后就正常了

**Comment by adaaaaaa** [comment]
Sun Dec  8 20:24:22 2019 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Dec  8 20:24:22 2019 user.notice dnsmasq: Allowing 127.0.0.0/8 responses

Sun Dec  8 20:24:24 2019 daemon.notice procd: /etc/rc.d/S95AdGuardHome: awk: /etc/AdGuardHome.yaml: No such file or directory
Sun Dec  8 20:24:24 2019 daemon.notice procd: /etc/rc.d/S95AdGuardHome: uci: Entry not found

这样的启动顺序是你说的那样吧？？

> 可能是启动顺序早于了dnsmasq

**Comment by rufengsuixing** [comment]
这不明显在dnsmasq后启动的

**Comment by rufengsuixing** [comment]
为什么不试着下载核心呢

**Comment by adaaaaaa** [comment]
> 为什么不试着下载核心呢

是这个吗？？
git clone https://github.com/AdguardTeam/AdGuardHome.git
搞了两个固件，一个有，一个没有这个。。。

**Comment by rufengsuixing** [comment]
那么大个按钮

**Comment by rufengsuixing** [comment]
你开心就好

**Comment by adaaaaaa** [comment]
> 那么大个按钮

更新核心吗？？

 Local version: ., cloud version: v0.99.3.
Updating core...
start download v0.99.3/AdGuardHome_linux_amd64.tar.gz
Failed to download core.

**Comment by rufengsuixing** [comment]
下载失败没什么好说的，找原因去吧

**Comment by rufengsuixing** [comment]
脚本位置在/usr/bin/AdGuardHome/update_core.sh

**Comment by adaaaaaa** [comment]
好像成功了。。。谢谢你，打扰你了。。。🤪🤪🤪

**Comment by adaaaaaa** [comment]
怎么手动添加规则给路由器里面的adguard呢？
it之家的广告去的不够彻底。。。
ublock就很彻底。。。

**Comment by adaaaaaa** [comment]
规则和ublock的通用吗？加上是不是就可以解决了？？😂

**Comment by rufengsuixing** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/issues/6
