### ISSUE TITLE
如何禁用掉这两个功能？

### ISSUE THREAD

**Issue by Mosney** [rufengsuixing/luci-app-adguardhome#24]
![image](https://user-images.githubusercontent.com/22477230/70615403-4db22e00-1c47-11ea-9807-38eff3938719.png)

**Comment by rufengsuixing** [comment]
手动设置里删掉dns 下upstream_dns 里除了你自己定义只外的所有条目

**Comment by Mosney** [comment]
可是这个上游服务器老是自动填充，一不小心就又保存到luci配置文件里了

**Comment by rufengsuixing** [comment]
填充了也没用，只要上面的是未添加就可以无视

**Comment by Mosney** [comment]
好吧 不知道干啥用的选项 还没有关闭选项 总觉得难受的慌
