### ISSUE TITLE
日志时间不对。。。

### ISSUE THREAD

**Issue by adaaaaaa** [rufengsuixing/luci-app-adguardhome#26]
2019/12/13 14:38:23 [info] Failed to do safebrowsing HTTP lookup, ignoring check: Get https://sb.adtidy.org/safebrowsing-lookup-hash.html?prefixes=FE8D3619/998F8033/DF46DB72/: dial tcp 176.103.133.133:443: connect: connection timed out
2019/12/13 14:35:23 [info] Entering the tcp listener loop on [::]:5553
2019/12/13 14:35:23 [info] Entering the UDP listener loop on [::]:5553

比北京时间慢了8小时。。。

**Comment by rufengsuixing** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1234

**Comment by rufengsuixing** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/commit/ecab453233b2086d1e48f1ebafb985595863a912
