### ISSUE TITLE
默认多加几个规则列表？？

### ISSUE THREAD

**Issue by adaaaaaa** [rufengsuixing/luci-app-adguardhome#27]
https://easylist-downloads.adblockplus.org/easylistchina.txt
https://easylist.to/easylist/easylist.txt
https://easylist.to/easylist/easyprivacy.txt

**Comment by rufengsuixing** [comment]
adh只是个dns过滤器，很多网页端的过滤规则要不是没有意义要不就是会严重的误伤。所以我只会加载host类的或者只有网址的过滤规则。

**Comment by adaaaaaa** [comment]
> 很多网页端的过滤规则要不是没有意义要不就是会严重的误伤。

emmm。。。规则是ublock弄下来的。。。好像添加到adh里面确实没有效果。。。
你说的没有意义或者误伤，我电脑端的ublock并不会啊？？为什么呢？

**Comment by rufengsuixing** [comment]
过滤原理不一样的，一个是内容过滤，一个是dns做的网址过滤
