### ISSUE TITLE
/lib/upgrade/keep.d/ 生成的目录疑似出错

### ISSUE THREAD

**Issue by Mosney** [rufengsuixing/luci-app-adguardhome#30]
![image](https://user-images.githubusercontent.com/22477230/70917116-b5a5b180-2057-11ea-8ac3-6914a7741a7e.png)
最后三行工作目录的部分两个//

**Comment by rufengsuixing** [comment]
工作目录结尾请不要加/，目录不需要斜杠结尾

**Comment by rufengsuixing** [comment]
实际上有/也能用，不行你试试//etc/

**Comment by Mosney** [comment]
晓得了，习惯了目录加个/以供标识
