### ISSUE TITLE
本地化日志时间选框不显示

### ISSUE THREAD

**Issue by Mosney** [rufengsuixing/luci-app-adguardhome#31]
https://github.com/rufengsuixing/luci-app-adguardhome/commit/b1e37c0133039b66b7a2e281565e149491e136e9 添加的本地化时间在我这显示不出，OpenWrt 19.07rc2
![image](https://user-images.githubusercontent.com/22477230/70917689-c0147b00-2058-11ea-9972-7b202eed285b.png)

**Comment by Mosney** [comment]
另外1.7.30的ipk中`/model/cbi/AdGuardHome/base.lua `好像没有添加新增的自动更新功能？

**Comment by rufengsuixing** [comment]
本地时间只会在log为文件时出现，你这个是系统日志，不会出现

**Comment by rufengsuixing** [comment]
另外release还没放出，着急可以自行编译

**Comment by Mosney** [comment]
好的清楚了
