### ISSUE TITLE
最新版本与ACC有冲突，只要启用了这个luci，ACC一定不会运行，废了！

### ISSUE THREAD

**Issue by zxlhhyccc** [rufengsuixing/luci-app-adguardhome#32]
### 提交之前

在你提交问题之前请回答以下问题
**你可以删掉提交之前这个部分**

- [ ] 我用着最新版的 luci-app-adguardhome
- [ ] 我检查了没有人提交同样的问题

**Comment by rufengsuixing** [comment]
本luci和acc无关
