### ISSUE TITLE
下载upx失败，路径判断有问题

### ISSUE THREAD

**Issue by ztechie** [rufengsuixing/luci-app-adguardhome#38]
Downloading http://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/x/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/x/Packages.gz

xz download fail
/usr/share/AdGuardHome/update_core.sh: line 129: xz: not found
Failed to download upx.

**Comment by rufengsuixing** [comment]
这个是你的opkg问题，你连不上opkg的源，重试直到成功，或者手动opkg install xz

**Comment by ztechie** [comment]
http://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/packages/packages.gz这才是正确的下载地址，里面下载地址被替换成x了，路径中x的位置应该是packages

**Comment by ztechie** [comment]
手动访问中间是x地址也是失败的

**Comment by ztechie** [comment]
我明天再看看，刚刚看了下代码，好像没网没问题，也可能是我固件的问题

**Comment by rufengsuixing** [comment]
修改你opkg的源
