### ISSUE TITLE
如果本身系统中已有adg二进制，建议增加一个检测执行文件版本功能，以便可以不使用更新功能！

### ISSUE THREAD

**Issue by zxlhhyccc** [rufengsuixing/luci-app-adguardhome#40]
### 提交之前

在你提交问题之前请回答以下问题
**你可以删掉提交之前这个部分**

- [ ] 我用着最新版的 luci-app-adguardhome
- [ ] 我检查了没有人提交同样的问题

**Comment by rufengsuixing** [comment]
自己的版本你可以在log中看到版本号，在不显著增大luci 负载的情况下可能一个按钮是比较好的选择

**Comment by rufengsuixing** [comment]
fix https://github.com/rufengsuixing/luci-app-adguardhome/commit/d13503838b31b15ca46094e0f3b13d8950182f3a
