### ISSUE TITLE
日志时间问题

### ISSUE THREAD

**Issue by ksong008** [rufengsuixing/luci-app-adguardhome#43]
![image](https://user-images.githubusercontent.com/54489832/71261358-201c6180-2378-11ea-88dd-60273bde1d38.png)
日志中的本地时间不打勾反而是本地时间

**Comment by rufengsuixing** [comment]
尝试刷新页面
emmm？有能力的话可以f12元素选择选中那个挑然后找附近的 var reverselog ，没能力的话，就算了

**Comment by rufengsuixing** [comment]
反正有一个是对的就行吧，2333

**Comment by rufengsuixing** [comment]
能提供更详细的日志么，比如浏览器控制台的报错等等

**Comment by yws112358** [comment]
一样的问题，应该就是 以为adghome 用的 +0区，实际adghome 使用的是当地时区  结果就反了
