### ISSUE TITLE
是否能对某个域名的不存缓存

### ISSUE THREAD

**Issue by doumeki** [rufengsuixing/luci-app-adguardhome#44]
如题, 请问怎么设置,是否有这个功能.
还有原始的cache time 我看是 cache_time: 30, 是什么单位啊?

**Comment by rufengsuixing** [comment]
本项目只是luci界面，关于手动配置的具体信息，请自行去程序开发页面寻找https://github.com/AdguardTeam/AdGuardHome

**Comment by rufengsuixing** [comment]
据我所知，现在没有这个功能

**Comment by doumeki** [comment]
感谢回复。之前看到说过开启ddns后请求全是127.1了，这个能否修复？不清楚为啥ddns还会和这个有冲突？

**Comment by rufengsuixing** [comment]
请使用替换dnsmasq功能

**Comment by doumeki** [comment]
我知道哈，我是在问另外的问题，sorry 没表达清楚.

**Comment by rufengsuixing** [comment]
开启ddns请求变多的原因是ddns使用nslookup自行请求的，如果用ddns的话又不能屏蔽这个请求，非要修复也就只能从日志入手，自我欺骗了

**Comment by doumeki** [comment]
好的，可能是我理解错了，我发现请求全是来自127.1的并非只是变多，而且我的也只是一小时才check一次ddns。我查了ipt也没有redirect53端口。可能是其他问题吧。

**Comment by rufengsuixing** [comment]
我说的是127.0.0.1查询localhost的较多，而你的是在说所有请求来源都是127，所以不一样，我的解决办法是重定向使用替换dnsmasq

**Comment by doumeki** [comment]
发完上面的我就明白为啥请求全是127.1了，我设置的是adgh为53的上游，所以dnsmasq转发的时候是变了src了，看来没法修复，哈哈。
