### ISSUE TITLE
第一次启动程序无法自动下载主程序

### ISSUE THREAD

**Issue by yangsongli** [rufengsuixing/luci-app-adguardhome#48]
AdGuard Home luci的版本:1.8-5
操作系统和版本:openwrt R9.12.03 x86架构
希望的执行结果
希望第一次启用程序后自动下载AdGuard Home主程序
实际的执行结果
第一次启动然后一直提示A task is already running. 就没有任何反应 必须要重启openwrt才会自动下载AdGuard Home主程序
日志
/tmp/AdGuardHome_update.log的日志只有A task is already running.
INIT_TRACE=1 /etc/init.d/AdGuardhome reload 2>/tmp/debug 后的/tmp/debug文件的日志只有-ash: /etc/init.d/AdGuardhome: not found
截图
![QQ截图20191226230737](https://user-images.githubusercontent.com/52395039/71480788-ddee9680-2835-11ea-8e57-94d0cffc7981.png)

**Comment by yangsongli** [comment]
已解决 单臂openwrt才会出现这种情况 有wan口就不会

**Comment by rufengsuixing** [comment]
A task is already running表示已经在下载了，最好不要打断下载进程

**Comment by rufengsuixing** [comment]
not found 表示你并没有成功安装

**Comment by rufengsuixing** [comment]
我会尝试优化正在更新时再次提交更新核心时的显示，尽量显示正在下载的日志而不是显示正在下载

**Comment by rufengsuixing** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/commit/5eecff1964885918504a156d6d7fe0db72a1221d
