### ISSUE TITLE
luci界面上关闭后，重新启用需要点两次保存并应用才能启用

### ISSUE THREAD

**Issue by liyiecho** [rufengsuixing/luci-app-adguardhome#49]
很久没关闭过，但最近发现luci界面上关闭后，重新启用需要点两次保存并应用才能启用。
目前版本1.8-7依然有这个问题。

点第一次保存并应用是这样的：
<img width="739" alt="QQ20191227-214621@2x" src="https://user-images.githubusercontent.com/5213722/71519434-7b0f0500-28f2-11ea-8962-c8619b8a83e8.png">
<img width="482" alt="QQ20191227-213936@2x" src="https://user-images.githubusercontent.com/5213722/71519465-99750080-28f2-11ea-8452-43f1b4afad5e.png">

点第二次保存并应用就正常启用了。
<img width="704" alt="QQ20191227-214711@2x" src="https://user-images.githubusercontent.com/5213722/71519492-b14c8480-28f2-11ea-9e0b-caa376cebe24.png">
<img width="487" alt="QQ20191227-215155@2x" src="https://user-images.githubusercontent.com/5213722/71519580-1f914700-28f3-11ea-9afa-0f5da687f983.png">

**Comment by rufengsuixing** [comment]
你的 ucitracktest为零，证明你的ucitrack至少在我这个luci这里是无效的，我这里的解决方法是第一次进行检测，当然第一次的提交是失效的，之后就会切换提交方式，就会正常

你可以测试一下是不是reload时机早于了提交配置，
具体来说就是拨动启用开关并提交保存是不是运行状态相反

**Comment by liyiecho** [comment]
固件版本	OpenWrt SNAPSHOT r11816-d5ede68f8b / LuCI Master git-19.360.66168-1ccb8e1
内核版本	4.19.91
<img width="859" alt="QQ20191227-232411@2x" src="https://user-images.githubusercontent.com/5213722/71522527-04790400-2900-11ea-89ae-81927ea87811.png">

luci界面上关闭应用，刚开始依然显示运行，此时后台查看AdGuardHome已经结束运行了，等待几秒后，luci界面才显示停止

**Comment by rufengsuixing** [comment]
运行状态同步总是会有延迟的，这个是正常的

**Comment by rufengsuixing** [comment]
close due to inactive
