### ISSUE TITLE
upx压缩用很长时间指的是多长时间？

### ISSUE THREAD

**Issue by geol** [rufengsuixing/luci-app-adguardhome#66]
- [√] 我用着最新版的 luci-app-adguardhome
- [√] 我检查了没有人提交同样的问题

MT7621的CPU。OpenWrt 19.07.2。
点击更新后，htop看到有个upx的进程。我昨晚点的更新，今天一看那进程还在。Luci上也还是没有更新完成（用的最好压缩，一开始没有执行文件，此时也没有），看了下耗时有10个多小时了。于是我kill掉那个upx的进程，然后在/usr/bin/AdGuardHome/就有了一个没有经过压缩的AdGuardHome可执行文件（~13.7MB）。
现在启动ADH后，我又点了下更新，半个小时过去了upx还没有处理完。所以，upx执行起来会耗费多久才能处理完？

**Comment by licsber** [comment]
我也想知道 现在你压缩好了没
我等了三个半小时了 感觉不太对劲才上来搜索一下

**Comment by geol** [comment]
> 我也想知道 现在你压缩好了没
> 我等了三个半小时了 感觉不太对劲才上来搜索一下

我已经放弃压缩了。
