### ISSUE TITLE
uci get 获得的flag值相反 导致开关相反

### ISSUE THREAD

**Issue by fuqiang03** [rufengsuixing/luci-app-adguardhome#7]
![QQ截图20191202133518](https://user-images.githubusercontent.com/26851715/69933179-c0fdc680-1508-11ea-9c32-64db41fcf3c2.png)
![QQ截图20191202133530](https://user-images.githubusercontent.com/26851715/69933182-c22ef380-1508-11ea-87f9-3202c89e1392.png)
openwrt master
必须手动shell 才可以运行

**Comment by rufengsuixing** [comment]
没能复现，需要更多信息

**Comment by fuqiang03** [comment]
openwt 主库代码 和luci  主库代码
控制页面无法启动adguardhome

**Comment by rufengsuixing** [comment]
给更详细的信息，不然我也没办法，至少我这边没有复现

**Comment by fuqiang03** [comment]
需要什么样的信息

**Comment by rufengsuixing** [comment]
页面有没有报错或者提交时打开浏览器控制台看看返回的页面有没有502或者404

**Comment by rufengsuixing** [comment]
或者系统日志报错信息

**Comment by rufengsuixing** [comment]
可能是库调用问题，我可以尝试修复一下

**Comment by fuqiang03** [comment]
root@OpenWrt:/# /etc/init.d/AdGuardHome start
fs error ln db to tmp /usr/bin/AdGuardHome overlay
这个是唯一的错误提示
只能用命令开启和关闭 
用命令开启后一切正常
可以进入页面

**Comment by fuqiang03** [comment]
貌似只有新版的luci -modules出现这样的问题

**Comment by rufengsuixing** [comment]
https://c-t.work/s/07b79766566a47
尝试一下

**Comment by fuqiang03** [comment]
这回能启动了 但是enable 的值好像判断反了
![QQ截图20191202193304](https://user-images.githubusercontent.com/26851715/69956350-b3f9cb00-153a-11ea-8061-509eb2e2d8b6.png)
这种状态是开启了

**Comment by rufengsuixing** [comment]
没有bin文件的情况下会自动下载bin文件，需要时间

**Comment by fuqiang03** [comment]
有bin的

**Comment by fuqiang03** [comment]
希望发布个分支 然后我测试下

**Comment by rufengsuixing** [comment]
我这边没有测试环境，我也不知道问题出在哪里，如果你有能力的话，可以试着提交pull request
相关代码在路由器的路径
/usr/lib/lua/luci/controller/AdGuardHome.lua 18-24行
\usr\lib\lua\luci\view\AdGuardHome\AdGuardHome_status.htm 
可以自行调试着修改，记得每次修改之后rm /etc/luci-indexcache 和rm /tmp/luci-modulecache/*
你可以测试一下如果bin路径为/usr/bin/AdGuardHomeAdGuardHome 时
pgrep /usr/bin/AdGuardHome/AdGuardHome  >/dev/null
echo $?
的返回值是否在进程存在时为0，不存在时为其他值

**Comment by fuqiang03** [comment]
我的 我这头测试成功后 会做个patch 
然后贴在这里 没弄过pull request

**Comment by rufengsuixing** [comment]
可以尝试删除各种local标签
比如
local uci=require"luci.model.uci".cursor()
改为
uci=require"luci.model.uci".cursor()

**Comment by fuqiang03** [comment]
收到  我先Git一下 再次编译一下看看

**Comment by rufengsuixing** [comment]
不用编译，直接在路由上修改就可以调试

**Comment by fuqiang03** [comment]
好的

**Comment by fuqiang03** [comment]
![QQ截图20191202203249](https://user-images.githubusercontent.com/26851715/69959892-11921580-1543-11ea-8844-88c888cb23d0.png)

**Comment by rufengsuixing** [comment]
这个结果没问题

**Comment by fuqiang03** [comment]
![QQ截图20191202205214](https://user-images.githubusercontent.com/26851715/69960991-c62d3680-1545-11ea-8849-ebe81b3e57b3.png)
改了他就正常了

**Comment by fuqiang03** [comment]
![QQ截图20191202205915](https://user-images.githubusercontent.com/26851715/69961402-beba5d00-1546-11ea-9f35-3f20c76ed3e5.png)
enabled 的值 都乱套了

**Comment by rufengsuixing** [comment]
![图片](https://user-images.githubusercontent.com/22387141/69961738-72bbe800-1547-11ea-9f7b-c4b594270f57.png)
和我这边的测试结果不同，我没法改

**Comment by rufengsuixing** [comment]
是不是传参的问题把后面2>/dev/null的当成参数了

**Comment by fuqiang03** [comment]
不会的
![QQ截图20191202211239](https://user-images.githubusercontent.com/26851715/69962257-93d10880-1548-11ea-9ee5-5c329c8d1a2e.png)
你的是版本是?

**Comment by fuqiang03** [comment]
读取的配置文件enabled值 是正确的 但是执行的时候不知道什么干扰了这个值

**Comment by rufengsuixing** [comment]
我这个是lean的op最新，
![图片](https://user-images.githubusercontent.com/22387141/69962399-e3afcf80-1548-11ea-9746-1bca02b5ee20.png)
我可以在Pandora上再次测试
![图片](https://user-images.githubusercontent.com/22387141/69962498-1f4a9980-1549-11ea-9b5c-a2be60ac9975.png)

**Comment by rufengsuixing** [comment]
就是说你的op版本
 test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
 test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
获得的值不同，其中前者是对的是么

**Comment by fuqiang03** [comment]
后者是对的

**Comment by rufengsuixing** [comment]
为啥，我枯了，这两个应该执行结果没区别，只是后者屏蔽了没有值的时候的报错信息

**Comment by rufengsuixing** [comment]
另外我用的是config_get获取的enable信息，所以我觉得可能是op最新版的bug，先不予修复，op应该会自行修复这个bug的
config_get_bool enabled $CONFIGURATION enabled 0

**Comment by rufengsuixing** [comment]
其他的应用enabled选项也反了么

**Comment by fuqiang03** [comment]
没有

**Comment by garypang13** [comment]
![111](https://user-images.githubusercontent.com/48883331/69963416-24a8e380-154b-11ea-9f6c-7bf88532b8ed.png)

OpenWrt R9.11.23 / LuCI Master (git-19.331.11944-c1039b9)

**Comment by fuqiang03** [comment]
lean的哦
知道了 
![QQ截图20191202213310](https://user-images.githubusercontent.com/26851715/69963608-85382080-154b-11ea-8faa-e4c6bade7b60.png)
![QQ截图20191202213345](https://user-images.githubusercontent.com/26851715/69963611-879a7a80-154b-11ea-83b9-401ae88e2677.png)

**Comment by fuqiang03** [comment]
![QQ截图20191202214406](https://user-images.githubusercontent.com/26851715/69964235-f5937180-154c-11ea-958b-f92e054b4f5b.png)
这都能反着执行

**Comment by rufengsuixing** [comment]
> ![QQ截图20191202214406](https://user-images.githubusercontent.com/26851715/69964235-f5937180-154c-11ea-958b-f92e054b4f5b.png)
> 这都能反着执行
你能给出更多的测试结果么，关于uci get ，确保操作的过程中没有其他命令尝试改变开关状态

**Comment by rufengsuixing** [comment]
test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
echo $test
test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
echo $test
尝试找一下其他配置文件里的flag量进行测试
