### ISSUE TITLE
首次打开，更新core，提示A task is already running.

### ISSUE THREAD

**Issue by raincity212** [rufengsuixing/luci-app-adguardhome#71]
感谢帮助，我是OpenWrt旁路由，预装本软件，第一次打开设置，然后更新程序，下方直接出现“A task is already running.” 然后就没有任何反应了，请问如何解决呢？

**Comment by raincity212** [comment]
已经搞定，手动把/usr/share/AdGuardHome/update_core.sh下相关代码注释掉就ok了

**Comment by jackblue200043** [comment]
![image](https://user-images.githubusercontent.com/55248478/96280702-e1dce680-100a-11eb-8a6f-f54e989daf43.png)

**Comment by uamrws** [comment]
最好不要注释掉/usr/share/AdGuardHome/update_core.sh 的代码
可以在执行校验查询前增加sleep
check_if_already_running(){
        sleep 1
        running_tasks="$(ps |grep 'AdGuardHome' |grep 'update_core' |grep -v 'grep' |
        [ "${running_tasks}" -gt "2" ] && echo -e "\nA task is already running."  &&
}
