### ISSUE TITLE
最新版op luci开关反置

### ISSUE THREAD

**Issue by Mosney** [rufengsuixing/luci-app-adguardhome#8]
### 提交之前

在你提交问题之前请回答以下问题
**你可以删掉提交之前这个部分**

- [Y] 我用着最新版的 luci-app-adguardhome
- [Y] 我检查了没有人提交同样的问题

### 问题详细信息

* **AdGuard Home luci的版本:**
  * 1.7-8
* **AdGuard Home server的版本:**
  * 0.99.3
* **操作系统和版本:**
  * 
	OpenWrt 19.07.0-rc1 r10649-c4fdb377a2 / LuCI openwrt-19.07 branch git-19.332.23110-3e90684

> 勾选时，实际作用为禁用。不勾选时，实际作用为启用
> 
> ![image](https://user-images.githubusercontent.com/22477230/69934082-e50ed700-150b-11ea-80d5-86ba55972968.png)
>

**Comment by Mosney** [comment]
手动编辑luci配置文件后解决，似乎是因为之前独立的ADG二进制在运行的缘故

**Comment by Mosney** [comment]
启动脚本第9行开始似乎是把binpath和configpath写死了？
```
config_get configpath $CONFIGURATION configpath "/etc/AdGuardHome.yaml"
config_get binpath $CONFIGURATION binpath "/usr/bin/AdGuardHome/AdGuardHome"
```
实测会出现不按luci的配置放置/执行二进制的情况出现，另外同时也的确是存在开关反置现象，看了半天启动脚本和lua也没看出个所以然，只能描述一下观察到的现象。

**Comment by Mosney** [comment]
贴一下目前的配置，在使用syslog时luci的日志显示功能也不正常。
```

config AdGuardHome 'AdGuardHome'
	option httpport '3000'
	option redirect 'none'
	option configpath '/etc/AdGuardHome.yaml'
	option verbose '0'
	option version 'v0.99.3'
	option gfwupstream ' '
	option workdir '/var/AdGuardHome/'
	option logfile 'syslog'
	option binpath '/usr/bin/AdGuardHome'
	option lastbinpath '/usr/bin/AdGuardHome'
	list old_redirect 'none'
	list old_port '53'
	list old_enabled '1'
	option enabled '1'


```

**Comment by Mosney** [comment]
另外也不是很懂`gfw列表上游服务器`这个选项有什么用途，README里似乎也没有具体说明。

**Comment by rufengsuixing** [comment]
开关相反是op新版luci的bug，在uci get 或者config get 时会获取和其他op版本相反的值，只涉及到最新版本op，不会修复，等待op官方修复

**Comment by rufengsuixing** [comment]
syslog，确实写入日志是不能用的，这个是adh自己的bug

**Comment by rufengsuixing** [comment]
gfw列表上游服务器在没有点击添加gfw加入列表之前是没有用的，如果用不到此功能，可以不用管这个值

**Comment by rufengsuixing** [comment]
关于luci在脚本中获取配置的方式可以参照luci的wiki，你看到的写死是没有值时的默认值

**Comment by rufengsuixing** [comment]
手动配置时，在配置提交前会调用二进制对配置文件进行检查，应该不会出现意外启动的情况

**Comment by Mosney** [comment]
> syslog，确实写入日志貌似是不能用的，这个是adh自己的bug，另外能用的话也没有必要在这里显示系统日志

之前用二进制+配置文件跑的时候是可以写入syslog的，可能是通过`-l`指定的log文件不支持syslog？

**Comment by rufengsuixing** [comment]
我测试了，syslog可用，并且我也更新了一下支持syslog日志在日志中显示，稍等我会发布release

**Comment by rufengsuixing** [comment]
注意syslog有时候会失败，这是AdG的锅
/usr/bin/AdGuardHome/AdGuardHome -c /etc/AdGuardHome.yaml -
p 3000 -w /usr/bin/AdGuardHome -l syslog
2019/12/04 02:59:53 [fatal] cannot initialize syslog: Unix syslog delivery error

**Comment by rufengsuixing** [comment]
你可以测试打印下
test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
echo $test
test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
echo $test

**Comment by rufengsuixing** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/issues/7

**Comment by rufengsuixing** [comment]
test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
echo $test
test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
echo $test
能提供下测试结果么，确保测试过程中没有修改enabled

**Comment by liyiecho** [comment]
1对应停止运行，0对应运行中
<img width="636" alt="QQ20191204-190428@2x" src="https://user-images.githubusercontent.com/5213722/70137469-ec2f1400-16c8-11ea-9aa1-7acfa49b7a4f.png">

<img width="864" alt="QQ20191204-190333@2x" src="https://user-images.githubusercontent.com/5213722/70137418-d1f53600-16c8-11ea-97d0-c60e53936dbd.png">

**Comment by liyiecho** [comment]
发现是`killall -q /usr/bin/AdGuardHome/AdGuardHome`这条命令的问题，执行这条命令无法结束程序运行

**Comment by rufengsuixing** [comment]
如果path路径正确的话，这条命令应该没问题啊，可以去掉-q再试看看有没有报错

**Comment by liyiecho** [comment]
killall: /usr/bin/AdGuardHome/AdGuardHome: no process killed
![image](https://user-images.githubusercontent.com/5213722/70139821-4a122a80-16ce-11ea-8489-8a0f05d93e44.png)
![image](https://user-images.githubusercontent.com/5213722/70139870-66ae6280-16ce-11ea-9d24-d31413151966.png)

**Comment by rufengsuixing** [comment]
这个确实是一个bug，我尝试修复一下

**Comment by rufengsuixing** [comment]
你可以尝试release

**Comment by liyiecho** [comment]
现在需要点两次保存并应用才能得到正确的，AdGuardHome.AdGuardHome.old_enabled的值对应相应的状态
![image](https://user-images.githubusercontent.com/5213722/70145011-189f5c00-16da-11ea-8dd2-c2bdae2f5c44.png)

**Comment by rufengsuixing** [comment]
AdGuardHome.AdGuardHome.old_enabled 对应的只是对于重定向的设置，只影响到redirect，不会影响程序启动

**Comment by liyiecho** [comment]
你看点两次保存并应用的结果里面enabled值不变，而old_enabled的值却改变了，按理来说，第二次点保存并应用不会改变old_enabled的值

**Comment by rufengsuixing** [comment]
old 表示的是开关上一次的状态，连续两次应用，开关值不变，必然记录enable值

**Comment by liyiecho** [comment]
enable值为0且old_enabled为1时，AdGuardHome还存活
![image](https://user-images.githubusercontent.com/5213722/70151033-f6134000-16e5-11ea-8668-4aee3af29040.png)
enable值为0且old_enabled为0时，AdGuardHome停止运行
![image](https://user-images.githubusercontent.com/5213722/70151539-b436c980-16e6-11ea-87f1-363359a2b6f2.png)

**Comment by rufengsuixing** [comment]
总觉得是其他问题导致了表面上看到的开关相反的问题

**Comment by Mosney** [comment]
> test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
> echo $test
> test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
> echo $test
> 能提供下测试结果么，确保测试过程中没有修改enabled

1.7-8版本下正常使用状态下测得的结果
```
root@OP19:~# test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
root@OP19:~# echo $test
1
root@OP19:~# test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
root@OP19:~# echo $test
1
root@OP19:~# 
```
附上此时的配置 
```
root@OP19:~# uci show AdGuardHome
AdGuardHome.AdGuardHome=AdGuardHome
AdGuardHome.AdGuardHome.httpport='3000'
AdGuardHome.AdGuardHome.redirect='none'
AdGuardHome.AdGuardHome.configpath='/etc/AdGuardHome.yaml'
AdGuardHome.AdGuardHome.verbose='0'
AdGuardHome.AdGuardHome.version='v0.99.3'
AdGuardHome.AdGuardHome.workdir='/var/AdGuardHome/'
AdGuardHome.AdGuardHome.logfile='syslog'
AdGuardHome.AdGuardHome.binpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.lastbinpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.enabled='1'
AdGuardHome.AdGuardHome.old_redirect='none'
AdGuardHome.AdGuardHome.old_port='53'
AdGuardHome.AdGuardHome.old_enabled='1'
```

**Comment by Mosney** [comment]
以下是1.7-16版本由开启状态取消勾选启用并保存应用后的测试结果 ，问题依旧
```
root@OP19:~# test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
root@OP19:~# echo $test
0
root@OP19:~# test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
root@OP19:~# echo $test
0
root@OP19:~# uci show AdGuardHome
AdGuardHome.AdGuardHome=AdGuardHome
AdGuardHome.AdGuardHome.httpport='3000'
AdGuardHome.AdGuardHome.redirect='none'
AdGuardHome.AdGuardHome.configpath='/etc/AdGuardHome.yaml'
AdGuardHome.AdGuardHome.verbose='0'
AdGuardHome.AdGuardHome.version='v0.99.3'
AdGuardHome.AdGuardHome.workdir='/var/AdGuardHome/'
AdGuardHome.AdGuardHome.logfile='syslog'
AdGuardHome.AdGuardHome.binpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.lastbinpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.old_redirect='none'
AdGuardHome.AdGuardHome.old_port='53'
AdGuardHome.AdGuardHome.old_enabled='1'
AdGuardHome.AdGuardHome.enabled='0'
AdGuardHome.AdGuardHome.gfwupstream='tcp://208.67.220.220#5353'

```
![image](https://user-images.githubusercontent.com/22477230/70260824-0ef62100-17cc-11ea-99c4-3a6b165cbbdf.png)

**Comment by Mosney** [comment]
以下是1.7-16版本由上步实际运行状态勾选启用并保存应用后的测试结果 ，

```

root@OP19:~# test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
root@OP19:~# echo $test
1
root@OP19:~# test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
root@OP19:~# echo $test
1
root@OP19:~# uci show AdGuardHome
AdGuardHome.AdGuardHome=AdGuardHome
AdGuardHome.AdGuardHome.httpport='3000'
AdGuardHome.AdGuardHome.redirect='none'
AdGuardHome.AdGuardHome.configpath='/etc/AdGuardHome.yaml'
AdGuardHome.AdGuardHome.verbose='0'
AdGuardHome.AdGuardHome.version='v0.99.3'
AdGuardHome.AdGuardHome.workdir='/var/AdGuardHome/'
AdGuardHome.AdGuardHome.logfile='syslog'
AdGuardHome.AdGuardHome.binpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.lastbinpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.gfwupstream='tcp://208.67.220.220#5353'
AdGuardHome.AdGuardHome.old_redirect='none'
AdGuardHome.AdGuardHome.old_port='53'
AdGuardHome.AdGuardHome.old_enabled='0'
AdGuardHome.AdGuardHome.enabled='1'

```

**Comment by Mosney** [comment]
刚刚在上步状态下未作任何更改，仅重新点击了一下“保存并应用”按钮，提示“没有待应用的更改”，返回后发现状态变为运行，至此实际运行状态与开关匹配，配置文件数据如下所示。
```
root@OP19:~# uci show AdGuardHome
AdGuardHome.AdGuardHome=AdGuardHome
AdGuardHome.AdGuardHome.httpport='3000'
AdGuardHome.AdGuardHome.redirect='none'
AdGuardHome.AdGuardHome.configpath='/etc/AdGuardHome.yaml'
AdGuardHome.AdGuardHome.verbose='0'
AdGuardHome.AdGuardHome.version='v0.99.3'
AdGuardHome.AdGuardHome.workdir='/var/AdGuardHome/'
AdGuardHome.AdGuardHome.logfile='syslog'
AdGuardHome.AdGuardHome.binpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.lastbinpath='/usr/bin/AdGuardHome'
AdGuardHome.AdGuardHome.gfwupstream='tcp://208.67.220.220#5353'
AdGuardHome.AdGuardHome.enabled='1'
AdGuardHome.AdGuardHome.old_redirect='none'
AdGuardHome.AdGuardHome.old_port='53'
AdGuardHome.AdGuardHome.old_enabled='1'


root@OP19:~# test=$(uci get AdGuardHome.@AdGuardHome[0].enabled)
root@OP19:~# echo $test
1
root@OP19:~# test=$(uci get AdGuardHome.@AdGuardHome[0].enabled 2>/dev/null)
root@OP19:~# echo $test
1

```

**Comment by Mosney** [comment]
根据以上三条，看起来是实际运行状态与`old_enabled`匹配。
状态与开关匹配之后与之前的配置文件就只有这一项存在差异，且可以明显看出在这个过程中发生变更的配置只有三条`old_`。
另外没看懂保留上次的部分配置有何意义。

**Comment by Mosney** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/issues/8#issuecomment-562254554
经过重复测试，以上步骤可以稳定复现，基本可以确定是跟这三个上次状态的配置项有关系，实际问题应该是启动脚本逻辑判断上顺序的问题。
目前lean的luci相关代码均落后于目前官方分支的两个19.07的rc版本，应该是由于新版的luci导致这个问题暴露出来。

**Comment by rufengsuixing** [comment]
结果如果和你说的一致，我的结论是，配置未完全写入时触发了reload，我会在reload前添加一个一秒的延时

**Comment by liyiecho** [comment]
1.7-17版本，无论点几次“保存并应用”按钮，显示停止的还是停止不会启动，运行的还是运行不会停止
<img width="636" alt="QQ20191204-190428@2x" src="https://user-images.githubusercontent.com/5213722/70137469-ec2f1400-16c8-11ea-9aa1-7acfa49b7a4f.png">
也不会改变old_enabled的值，old_enabled为1时，AdGuardHome还存活，只能手动`/etc/init.d/AdGuardHome stop`来停止
![54AF1061-DEDD-47B8-948D-A01B3968B7B6](https://user-images.githubusercontent.com/5213722/70295604-979fac00-1822-11ea-9e5a-bac5e4d1c5e0.png)
![55C56CE6-9011-4BF5-B822-EE31A343C495](https://user-images.githubusercontent.com/5213722/70296484-c9fed880-1825-11ea-9c1c-969bd3dcf0cf.png)
手动执行命令来看enable值没变，改变的是old_enabled，且old_enabled的值刚好对应状态
<img width="695" alt="QQ20191206-123310@2x" src="https://user-images.githubusercontent.com/5213722/70296206-b1da8980-1824-11ea-87fa-c679ff24e4a7.png">

**Comment by rufengsuixing** [comment]
启动命令加载失误了，已修复

**Comment by liyiecho** [comment]
1.7-18版可以正常控制了，但还是有个小问题，当从停用状态到启用状态时`AdGuardHome.AdGuardHome.enabled='1'`，`AdGuardHome.AdGuardHome.old_enabled`应该为0，可现在却是1
<img width="753" alt="QQ20191206-144447@2x" src="https://user-images.githubusercontent.com/5213722/70302190-59f94e00-1837-11ea-9422-68dc5cbc3a58.png">

**Comment by rufengsuixing** [comment]
old_enabled 是为了控制重定向功能的，会检测两次开关状态来决定是否改动防火墙或者dnsmasq规则，因为现在我没有实现快速reload，可能用处少一点

**Comment by rufengsuixing** [comment]
已经实现了快速reload

**Comment by Mosney** [comment]
1.7-21测试正常
