### ISSUE TITLE
非常困惑   关于国外网站去广告的问题

### ISSUE THREAD

**Issue by zhea55** [rufengsuixing/luci-app-adguardhome#80]
我在n1上安装了luci-app-adguardhome

国内网站去广告是没问题的。

国外网站去广告，假设在passwall里面，chinaDNS-ng里面，国外dns也指向adguard的端口。

那么是不是远程VPS主机每次都要向我本地发起dns的请求，本地的adguard home来对请求的dns进行过滤。

这样一个工作模式，是可以工作，但是感觉效率太低，速度也很慢，特别是vps套了cdn的情况。

**Comment by FishMagic** [comment]
我刚刚进行了一些测试，如果将 passwall 中的 DNS 地址设置为本身的 IP 甚至是我远程 ADH 服务器的IP 都会导致国外网站无法正常解析 DNS，非常令人迷惑
