### ISSUE TITLE
[功能请求]增加清除日志功能或逆序查看日志

### ISSUE THREAD

**Issue by Mosney** [rufengsuixing/luci-app-adguardhome#9]
**查看日志的时候不太方便，可以有两个解决思路。**

> -  倒序展示日志，这样最新的日志在最上方，不需要拖到最下面去看新日志，问题是OP可能没有翻遍的倒序查看实现。

> - 在luci的log处增加一个清除日志的按钮，方便查看最新日志信息，例如[openclash](https://github.com/vernesong/OpenClash) 日志页
> ![image](https://user-images.githubusercontent.com/22477230/69934823-26a08180-150e-11ea-8f96-61fdbcba9122.png)

**Comment by rufengsuixing** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/pull/11
