### ISSUE TITLE
核心版本更新到最新版本0.103.3 报错:  

### ISSUE THREAD

**Issue by liangjunheng** [rufengsuixing/luci-app-adguardhome#91]
核心版本更新到最新版本0.103.3 报错:  

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute function dispatcher target for entry '/admin/services/AdGuardHome'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/AdGuardHome/base'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/AdGuardHome/base.lua:49: attempt to concatenate local 'version' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by h31105** [comment]
openwrt adguard 的更新界面无法更新，可以通过adguard面板更新到最新版
但更新后，openwrt adguard 页面无法识别新版本。（不影响使用

**Comment by liangjunheng** [comment]
> openwrt adguard 的更新界面无法更新，可以通过adguard面板更新到最新版
> 但更新后，openwrt adguard 页面无法识别新版本。（不影响使用

这个我是知道的，所以想反馈一下。功能正常，路由器界面进不去了

**Comment by liangjunheng** [comment]
> openwrt adguard 的更新界面无法更新，可以通过adguard面板更新到最新版
> 但更新后，openwrt adguard 页面无法识别新版本。（不影响使用

希望作者可以修复下

**Comment by ameshkov** [comment]
@rufengsuixing hi! we changed the AGH version string, you need to strip the "v" prefix when comparing versions

**Comment by cnstark** [comment]
应该是因为没有version变量导致的，我把/usr/lib/lua/luci/model/cbi/AdGuardHome/base.lua 49行注释掉并重新对e赋值，lua界面就可以打开了
![image](https://user-images.githubusercontent.com/45590791/88993574-edc4e080-d318-11ea-92e4-23983a8d704f.png)
不过影响了版本号的获取，但插件可以正常使用
![image](https://user-images.githubusercontent.com/45590791/88993612-03d2a100-d319-11ea-8cfe-4689dcd8cdef.png)

**Comment by liangjunheng** [comment]
> 应该是因为没有version变量导致的，我把/usr/lib/lua/luci/model/cbi/AdGuardHome/base.lua 49行注释掉并重新对e赋值，lua界面就可以打开了
> ![image](https://user-images.githubusercontent.com/45590791/88993574-edc4e080-d318-11ea-92e4-23983a8d704f.png)
> 不过影响了版本号的获取，但插件可以正常使用
> ![image](https://user-images.githubusercontent.com/45590791/88993612-03d2a100-d319-11ea-8cfe-4689dcd8cdef.png)


可以，完美解决进入界面问题
