### ISSUE TITLE
AdGuard Home server v0.103.3版本mips构架文件名称改变造成luci页面升级只能下载到0.102版本的文件

### ISSUE THREAD

**Issue by mlwrx1978** [rufengsuixing/luci-app-adguardhome#98]
### 提交之前
- [ ] 我用着最新版的 luci-app-adguardhome
- [ ] 我检查了没有人提交同样的问题

### 问题详细信息

AdGuard Home server v0.103.3版本mips构架文件名称改变造成luci页面升级只能下载到0.102版本的文件
v0.102版本文件名称是AdGuardHome_linux_mips.tar.gz而v0.103版本的文件名称是AdGuardHome_linux_mips_softfloat.tar.gz
新版mips构架的4个文件名称都多了” _softfloat “  
在升级用的下载链接里面添加这些字符后可以下载到正确的新版文件
更新后luci页面显示 核心版本:core error 但是不影响正常使用
* **AdGuard Home luci的版本:**
  * <v1.8-11>
* **AdGuard Home server的版本:**
  * <v0.103.3>
* **操作系统和版本:**
  * <OpenWrt mips 构架  >

**Comment by kongfl888** [comment]
下载并测试： [link](https://github.com/rufengsuixing/luci-app-adguardhome/pull/101)

**Comment by mlwrx1978** [comment]
可以了 谢谢
